[package]
name = "gf32"
version = "0.1.0"
edition = "2021"

[features]
bauble = ["dep:bauble"]

[dependencies]
bauble = {git = "https://github.com/Cakefish/bauble.git", rev="e70b30845ad68ccf7ac33b31f6257a70d1581a43", optional = true}
thiserror = "^1.0"
