[package]
name = "gf32"
version = "0.1.0"
edition = "2021"

[features]
bauble = ["dep:bauble"]

[dependencies]
bauble = {git = "https://github.com/Cakefish/bauble.git", optional = true}
thiserror = "^1.0"
